import React from "react";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "styles/globals.css";
import StoreProvider from "./StoreProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Game Engine",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <StoreProvider>
            <html lang="en">
            <body className={inter.className}>{children}</body>
            </html>
        </StoreProvider>
    );
}